services:
  - type: web
    name: telegram-file-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: DB_CHANNEL_ID
        sync: false
      - key: FORCE_SUB_CHANNEL
        sync: false
      - key: BOT_USERNAME
        sync: false
      - key: WEBHOOK_URL
        sync: false
